name: flutter_assessment_app
description: "A professional Flutter project for SSS Stars assessment."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.0
  dio: ^5.4.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  firebase_storage: ^11.6.9
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.14.4
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  build_runner: ^2.4.8
  isar_generator: ^3.1.0+1
  riverpod_generator: ^2.4.0
  golden_toolkit: ^0.15.0
  mocktail_image_network: ^1.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/

  fonts:
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/sf-pro-text-medium.otf
          weight: 500
        - asset: assets/fonts/sf-pro-text-bold.otf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
    - family:  DMSans
      fonts:
        - asset: assets/fonts/DMSans_18pt-Bold.ttf
          weight: 700
    - family:  inter
      fonts:
        - asset: assets/fonts/Inter_24pt-Bold.ttf
          weight: 700